### ISSUE TITLE
Collection Not Sorted Correctly

### ISSUE THREAD

**Issue by minerick** [ilkermutlu/laravel-gloss#1]
The result set I am getting is not sorted correctly in alphabetical order. The foreach loop that I run provides the following result:

A B C T D E F G H I K L M N O P R S V W Y J Q U

The only thing am doing differently from the example provided is the table fields that I am pulling: `$records = DB::select(DB::raw('SELECT name, url FROM people'));`

Suggested change to fix issue is to call `->sort()` method on the `$collection` property in the `createFrom` method:

```
public function createFrom(Array $array = null, Collection $collection = null)
    {
        if ($array) {
            $collection = new Collection($array);
            $this->collection = $collection;
        }

        if ($collection) {
            $this->collection = $collection->sort();
        }
        return $this;
    }

```

**Comment by ilkermutlu** [comment]
Should be resolved by 500e96ba5f2950663c1d569d64ac689c1b29e285

Closing the issue for now.
